version: "3.9"

services:
  postgres:
    image: postgres:16.6
    container_name: postgres_db_ps
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: vinhnima
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

  vinhnima:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: vinhnima-api
    ports:
      - "8089:8080"
      - "9991:9990"
    environment:
      DATASOURCE_NAME: PostgresDS
      DATASOURCE_JNDI: java:jboss/jdbc/PostgresDS
      POSTGRESQL_VERSION: 42.6.0
      JBOSS_HOME: /opt/jboss/wildfly
      VALID_CONNECTION_CHECKER: org.jboss.jca.adapters.jdbc.extensions.postgres.PostgreSQLValidConnectionChecker
    depends_on:
      - postgres
    volumes:
      - ./target:/app/target
      - maven_cache:/root/.m2

volumes:
  postgres_data:
  maven_cache:
